pipeline {
    agent none 
    stages {
        stage('pre-parallel') {
            steps{
                echo 'Running pre-parallel stage'
            }
        }
        stage('Parallel build Pipelines') {
            parallel {
                stage('macOS Pipeline') {
                    agent { label 'macos' }
                    stages {
                        stage('macOS Build') { 
                            steps {
                                dir('src/BuildScripts') {
                                    sh './build.macos.sh' 
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('Parallel test pipelines') {
            parallel {
                stage('macOS Pipeline') {
                    agent { label 'macos' }
                    stages {
                        stage('macOS Test') { 
                            steps {
                                dir('src/vmm/tests') {
                                    echo '----------=====### Starting Tests ###=====----------'
                                    sh 'ls -l'
                                    sh '/opt/homebrew/bin/py.test --junit-xml test-reports/results.xml test_*.py'
                                    // sh '/Users/jenkins/.pyenv/shims/python ./test_run_commands.py'
                                    //sleep 15
                                    echo '----------=====### Finished Tests ###=====----------'
                                    junit 'test-reports/results.xml' 
                                }
                            }
                        }
                    }
                }
            }
        }
        stage('post-parallel') {
            steps {
                echo 'Running post-parallel stage'
            }
        }
    }
}
